### ISSUE TITLE
FlatList Doc

### ISSUE THREAD

**Issue by LouisJS** [facebook/react-native-website#102]
It seems like the FlatList component is recommended in every version of the doc, even though it was only introduced from 0.43.

It would be better to provide a proper ListView docs for the version anterior to 0.43

**Comment by hramos** [comment]
Hi LouisJS, this is intentional as every doc under Guides is being treated as "unversioned". What this means is that we will show the same up to date content, regardless of which version of the site you're looking at. Ultimately, the goal of the version switcher is to show you the API and Component docs for that given version. The Guides, though, remain the same regardless of which version you are looking at.

You can always find ListView docs under the API/Components sections when looking at 0.43 and below.
