### ISSUE TITLE
Text {'\n'} dosen't display new lines correctly in preview

### ISSUE THREAD

**Issue by MBLHarrison** [facebook/react-native-website#1056]
In the [Text](https://facebook.github.io/react-native/docs/text#accessibilitylabel) documents, the first example is meant to be showing new lines, but on the actual mobile output accompanying it, there are no new lines where there should be.

![image](https://user-images.githubusercontent.com/17315707/60028226-e0a9dc80-9696-11e9-8ae8-652366af395f.png)

After the header in the bigger bold text, there should be two new lines.

**Comment by realPrimoh** [comment]
Hm... it should just be {\n} for a new line.

**Comment by Simek** [comment]
@MBLHarrison It seems like issue described here is no longer valid, can you confirm that?

**Comment by MBLHarrison** [comment]
@Simek When using Expo with iOS and Android it displays as it should, however for me the web is not rendering at all. is that a separate issue though

**Comment by Simek** [comment]
@MBLHarrison It's obvious for me that this is not RN website issue. `expo` or `react-native-web` could be the culprit. But since you have reported it here i would like to investigate.

Can you tell me which OS and browser you are using?

It looks okay for me on Chrome of macOS and Win:
<img width="604" alt="Annotation 2020-03-15 190614" src="https://user-images.githubusercontent.com/719641/76707556-5b68cb00-66f0-11ea-99d8-3a0027452300.png">

Please try Snack on the Text page:
https://reactnative.dev/docs/next/text

**Comment by MBLHarrison** [comment]
Win 10
It _doesn't_ work on Brave.
Just tested and it _does_ work on Edge and Firefox.

**Comment by Simek** [comment]
So it might be even issue specific only to the Brave browser. 

I would recommend to report this bug elsewhere (presumably in `react-native-web` repo or Brave support/bug track) because React Native website maintainers have no ability to fix this in any way.
