### ISSUE TITLE
FlatList More complex, multi-select example 

### ISSUE THREAD

**Issue by hossamnasser938** [facebook/react-native-website#1529]
The example provided in the FlatList article is supposed to rerender the FlatList only when passing extraData prop. However, the FlatList rerenders on IOS and Android whether extraData prop is passed or not. The strange thing is that the example works fine on web.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/27894818/71522930-71c07100-28cf-11ea-8c09-48efb71d7bba.gif)

**Comment by HectorRicardo** [comment]
I believe there is a mistake in this example. The documentation of FlatList states that:

> This is a PureComponent which means that it will not re-render if props remain shallow-equal. Make sure that everything your renderItem function depends on is passed as a prop (e.g. extraData) that is not === after updates, otherwise your UI may not update on changes. This includes the data prop and parent component state.

The problem is that the `renderItem` prop is passed as an inline function, thus the section list will rerender in every App's rerender. Therefore, the extraData parameter is useless in this example. The documentation should show another example of how to use the extraData prop correctly.

**Comment by HectorRicardo** [comment]
Also, can you reword this phrase ?

> Make sure that everything your renderItem function depends on is passed as a prop (e.g. extraData) that is not === after updates, otherwise your UI may not update on changes.

Seems grammatically incorrect (which is the verb, "is" or "updates" ?).

**Comment by HectorRicardo** [comment]
@stale This should remain open
