### ISSUE TITLE
[Feature] Dark mode for website

### ISSUE THREAD

**Issue by cepem** [facebook/react-native-website#1639]
Hi!

I am planning on implementing a dark theme for the website. I looked over the issues and it looks like no one else is working on this.

However, I'd like to make sure. Therefore @rachelnabors what do you think?

**Comment by luism3861** [comment]
sounds good

**Comment by rachelnabors** [comment]
We haven't had any requests for a Darkmode that I know of. Is it necessary? If you were able to help us update the component docs #1579 would be a far greater contribution! But if you submit a PR for Darkmode, I'll review it.

**Comment by Naturalclar** [comment]
currently, react-native document is powered by `docusaurus` version 1.
`docusaurus` version 2 has support for dark mode by default.
Instead of trying to add dark mode support in the current document, I think it would be better to move on to docusaurus 2, once all the component docs are updated, and once docusaurus 2 supports versioning (which iirc not yet supported in the alpha version of docusaurus 2)

**Comment by cepem** [comment]
@Naturalclar good to know! I won't proceed with this then

**Comment by rachelnabors** [comment]
Closing this issue. Let's consider this Yet Another Reason to Upgrade!
