### ISSUE TITLE
Docs incorrectly state that "removeClippedSubviews" defaults to "true" for ScrollView

### ISSUE THREAD

**Issue by rufusraghunath** [facebook/react-native-website#1648]
The [documentation](removeClippedSubviews) states that `true` is the default value for `removeClippedSubviews` in the `ScrollView` component.

The [source code](https://github.com/facebook/react-native/blob/10254a900a2332fc87063d9287da2403abbdf5c3/Libraries/Components/ScrollView/ScrollView.js#L1085) shows that (unless it's Android and sticky headers are on), we just accept whatever prop value is passed to the component - so no default value.

We also observed a behavior change in our application when we switched to `removeClippedSubviews={true}` from not setting the prop at all, where we were not getting lazy rendering behavior unless we explicitly set it to `true`. This suggests that there is a mismatch between the docs and the actual implementation.

**Comment by rufusraghunath** [comment]
Happy to open a PR once I have clarity on whether the documentation or the implementation should change.

**Comment by gedeagas** [comment]
@rufusraghunath just cheeked the source code for `ScrollView` and found that since https://github.com/facebook/react-native/commit/efae175a8e1b05c976cc5a1cbd492da71eb3bb12 there has not been a default value for `removeClippedSubviews` in `ScrollView`. As for the docs, from the git history of react-native-website i think we need @hramos clarification on this matter.


And in `FlatList` since this commit https://github.com/facebook/react-native/commit/1a499f43b2d03cc27dd6c25c8f13a767862afba1 the default value of `removeClippedSubviews` on Android is true. This also suggests that there is a mismatch between the docs and the actual implementation. I think this need to be addressed as well.
https://reactnative.dev/docs/flatlist#removeclippedsubviews

**Comment by gedeagas** [comment]
@rufusraghunath Hi are you still planing to update the docs?

**Comment by rufusraghunath** [comment]
@gedeagas yes, I'll send a PR today.

**Comment by gedeagas** [comment]
Thats awesome ❤️

**Comment by rachelnabors** [comment]
![omgomgomgomg](https://user-images.githubusercontent.com/236306/76578424-70f7ae00-64c0-11ea-9cb0-5bb59140cde3.gif)
Thank you for handling this!!! We love when folks PR issues!
