### ISSUE TITLE
Google search results pointing to very old versions

### ISSUE THREAD

**Issue by TheSavior** [facebook/react-native-website#1768]
I searched Google for "React Native elevation"

![Screen Shot 2020-03-18 at 10 58 24 AM](https://user-images.githubusercontent.com/249164/76991794-6ba6c300-6907-11ea-807e-79355513826d.png)

The link for this is 
```
https://facebook.github.io/react-native/docs/0.52/view-style-props
```

0.52 is a really old release and the likelihood that the docs for that are very out of date. 

Is there any SEO we can do to help results default to the current version?

**Comment by yangshun** [comment]
What will be the right page here?

**Comment by TheSavior** [comment]
@rickhanlonii found this related issue from how Node solved this. https://github.com/nodejs/node-v0.x-archive/issues/941

**Comment by rickhanlonii** [comment]
My recommendation here for optimal SEO is:
- Add a /latest vanity URL (so we can set this up once and leave it run)
- Add ref="canonical" redirects to every versioned doc pointing to /latest
- Update the sitemap to remove the versioned docs, and only include /latest

If I understand indexing correctly, then with this strategy search engines will show the `/latest/<doc>` page for search terms that also exist on latest and fall back to the old version for terms that have been removed. An ideal may be that every n version points to the n+1 version so that we fall back to the newest version, but that's probably unnecessary for now.

This works because search engines use canonical links as hints for redirects and know how to handle cases like this. We just have to tell them which pages are the preferred pages. Right now we tell them all pages are equal weight so they have to use other signals. Doing this with both ref="canonical" and the sitemap is required so they don't conflict.

Note we currently include every versioned page in our sitemap which is a lot of duplication and we're asking google to crawl them every hour (we should fix this ASAP):

<img width="1109" alt="Screen Shot 2020-03-18 at 3 14 33 PM" src="https://user-images.githubusercontent.com/2440089/76998288-357b3a80-692b-11ea-873e-a6e075a2b8a6.png">

**Comment by TheSavior** [comment]
Our existing unversioned links are the latest ones, do we need a `/latest` vanity? Or can the existing URL be the canonical?

**Comment by rickhanlonii** [comment]
@TheSavior good point, the /docs URLs function as /latest, updated.

**Comment by rachelnabors** [comment]
I don't think this is the appropriate use of `canonical` given Google's guidelines. The feature is intended to point pages of duplicate content to a single "canonical" source (IIRC identical "meat" but the surrounding markup might differ—think mobile and desktop pages and reblogs).

Before we pursue `canonical` as a solution, let's get some data from other people who have used this solution. (Did this solve the problem for the Node community, or was the issue close after implementation and never revisited?)

I'll ask other documentation managers about their experiences. Let's not rush into implementing solutions just yet!

**Comment by lcelso** [comment]
I believe the search is still cached, as it is still indexing the old url and redirecting to the new one.

https://facebook.github.io/react-native/docs/0.56/view-style-props.

https://webcache.googleusercontent.com/search?q=cache:iFhOA-9kJF4J:https://facebook.github.io/react-native/docs/0.56/view-style-props+&cd=1&hl=en

The third search option falls on the most current page.

In my view we have some decision-making to be made:

- Some work really with SEO
- Advise the use of the most current version in the old pages.

**Comment by rickhanlonii** [comment]
Note that the majority of pages across versions are exact duplicates because they're unchanged. I think google is able to verify duplicate content so using canonical would work even for pages that are slightly different.

There's no need to be perfect here - we could try some options and see what works. One thing we know is definitely wrong is the sitemap.

**Comment by rickhanlonii** [comment]
I believe this is still an issue, @rachelnabors any work from other documentation managers about their experiences?

**Comment by yangshun** [comment]
@slorber something to take note

**Comment by Simek** [comment]
@TheSavior @rickhanlonii It looks like the migration to V2 have solved the issue, at least in my Google results. 😉 

<img width="685" alt="Screenshot 2020-11-03 143451" src="https://user-images.githubusercontent.com/719641/97991556-e6164b80-1de1-11eb-9547-1c166c980f69.png">

**Comment by slorber** [comment]
I don't have the 2nd link on my search results 😅

Not sure why the migration fixed this, but it may be due to docs linking to each others in different versions through the new dropdown (vs the old versions page). 

Will have to figure out if it's a good enough solution or if we can improve the SEO + docs versioning support.
