### ISSUE TITLE
"Warning: Failed propType:Invalid prop 'source' supplied to 'Image' 

### ISSUE THREAD

**Issue by MattGoldwater** [facebook/react-native-website#1876]
I'm going through the React Native tutorial with Expo on iOS and whenever I import an image I get the warning, ""Warning: Failed propType:Invalid prop 'source' supplied to 'Image'" and the image doesn't appear on the screen.

For example from [https://reactnative.dev/docs/intro-react](https://reactnative.dev/docs/intro-react)

```
import React from 'react';
import { Text, View, Image } from 'react-native';

export default function CatApp() {
  return (
    <View>
      <Image
        source="https://reactnative.dev/docs/assets/p_cat1.png"
        style={{width: 200, height: 200}}
      />
      <Text>Hello, I am your cat!</Text>
    </View>
  );
}
```

I was able to get the image to appear by adding a uri property as suggested in the accepted answer here: [https://stackoverflow.com/questions/36460827/react-native-failed-proptype-on-image-component/36460928](https://stackoverflow.com/questions/36460827/react-native-failed-proptype-on-image-component/36460928)

```
export default function CatApp() {
  return (
    <View>
      <Image
        source={{uri: "https://reactnative.dev/docs/assets/p_cat1.png"}}
        style={{width: 200, height: 200}}
      />
      <Text>Hello, I am your cat!</Text>
    </View>
  );
}
```

Is there something I'm missing? If not, I'd be glad to make the PR to fix it.

**Comment by Simek** [comment]
Hi @MattGoldwater, thank you for reporting this! The solution you have posted is correct, feel free to make it into a PR. I would be nice if you can edit also `0.62` [versioned page](https://github.com/facebook/react-native-website/blob/master/website/versioned_docs/version-0.62/intro-react.md) beside `current/next` one, because `0.62` docs are the default selected version (when user enters the website).
