### ISSUE TITLE
Accessibility Role 'textbox' not defined in documentation about accessibilityRole prop

### ISSUE THREAD

**Issue by jacquesdev** [facebook/react-native-website#1885]
I had a look here: https://reactnative.dev/docs/accessibility#accessibilityrole-ios-android, and it seems that a role is missing. Assuming that the roles are taken from the standard described here: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles it looks like textbox is missing, https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/textbox_role.

Essentially I am looking for a role which describes an input, and it seems that is the correct one to choose.

**Comment by Simek** [comment]
@jacquesdev As you can see in the [source code](https://github.com/facebook/react-native/blob/master/Libraries/Components/View/ViewAccessibility.js) React Native doesn't support `textbox` accessibility role right now. 

You should create an issue in the `react-native` [repository](https://github.com/facebook/react-native/issues) or start a discussion in the official `discussions-and-proposals` [repository](https://github.com/react-native-community/discussions-and-proposals).

Since it's the React Native Website repository we are not able handle your request here.
