### ISSUE TITLE
[FlatList]: Should the height of the ListHeaderComponent be included in the getItemLayout offset?

### ISSUE THREAD

**Issue by Lowisoft** [facebook/react-native-website#1891]
Hi, there is an ambiguity in the docs regarding the `getItemLayout` prop of `FlatList`.

Should the height of the `ListHeaderComponent` be included in the `getItemLayout` offset? 

So that we would get something like this:

```
getItemLayout={(data, index) => (
    {length: ITEM_HEIGHT, offset: HEADER_HEIGHT + ITEM_HEIGHT * index, index}
  )}
```
Because for the `scrollToOffset` prop for example, the height of the `ListHeaderComponent` is certainly included in the calculations.

Unfortunately, the docs only indicate that we must include the height of the `ItemSeparatorComponent `in the offset and I could not find any other trustable source that clarified this.

**Comment by RodolfoGS** [comment]
Someone know about this?

**Comment by Lowisoft** [comment]
> 
> 
> Someone know about this?

I've also asked the question on [Stack Overflow](https://stackoverflow.com/questions/61085600/flatlist-should-the-height-of-the-listheadercomponent-be-included-in-the-getite), but I've got no answer so far,

**Comment by pavel-roj** [comment]
Old issue, but I'll write this here if anyone needs it. I'd say include the height of the header component in the offset, since scrollToIndex doesn't scroll exactly to the item if the header height is not included inside of a list with a header.
![image](https://github.com/user-attachments/assets/d8b5bb32-ec7b-4168-a78b-dae7c8f3d675)
