### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by purezen** [facebook/react-native-website#2001]
## Description

1. Right sidebar has repeated links like on page https://reactnative.dev/docs/running-on-device for `Connecting to the development server` and `Building your app for production`

2. In `Connect via Wi-Fi` section, the instructions looks a bit outdated.

Where it is mentioned 

> Go to Dev Settings → Debug server host & port for device.

the route rather seems `Settings → Debug server host & port for device`

3. Camera Roll appears in searches but has broken links

Edit link on https://reactnative.dev/docs/cameraroll is broken. Don't know why Camera Roll is shown in search. If it is to be shown the `Edit` link might be updated.

## Documentation version
Present in the current version i.e. 0.62

Will be glad to open PR

**Comment by charpeni** [comment]
Thanks for flagging that @purezen!

Camera Roll may be outdated with broken links because it's deprecated and not included anymore.

Would love to review your pull requests for the other mentions. 😃

**Comment by 3scava1i3r** [comment]
@purezen those links are not repeated but they point to different panels of the same webpage

**Comment by roubalsehgal** [comment]
Yes, @3scava1i3r you're right but I think their hierarchy isn't correct because when the device is different links should be under their respective device. 

What do you say? @charpeni 

See image below ⤵

![Screenshot (211)](https://user-images.githubusercontent.com/44202409/88483344-cbcc0680-cf84-11ea-900e-5122da56eff3.png)

**Comment by 3scava1i3r** [comment]
the issue is that those links 
1. Plug in ..........
2. Configure code ...........
3. Build and Run your ..............
are dead links

**Comment by Simek** [comment]
Hi all 👋!

The problems described above are known issues caused by content switching tabs (platform and OS in this case). For the same reason the right sidebar has been disabled on the [Environment Setup](https://reactnative.dev/docs/environment-setup) page. 

Within the current docs platform restrictions (Docusaurus V1) it is not possible to fix this problem cleanly in our codebase. Unfortunately the only solution for now is to disable the `onPageNav` (the right sidebar).

**Comment by Simek** [comment]
@purezen Can you confirm that reported issues has been fixed for you?

**Comment by purezen** [comment]
Looks good (y)

**Comment by Simek** [comment]
@purezen Awesome, thank you! 🙂
