### ISSUE TITLE
Switch component showing broken example on web

### ISSUE THREAD

**Issue by chanonroy** [facebook/react-native-website#2032]
## Description

<img width="849" alt="Screenshot 2020-07-09 at 12 07 18 pm" src="https://user-images.githubusercontent.com/16366896/87032624-d04e9c00-c1dc-11ea-9575-22e78d9929aa.png">

As a developer trying to use the Switch component, when I look at the example documentation [here](https://reactnative.dev/docs/switch#example), I am given a web expo snack example that is currently broken (the component props are not working on the web example), which leads me to confusion about what the props do.

It would be better if we could default the expo snack to the Android or iOS example, instead of web.

It would also be great to investigate what the underlying issue with why the web component doesn't work as intended 🤔 

### 0.63
https://reactnative.dev/docs/switch#example

**Comment by Simek** [comment]
@chanonroy Thank you for bringing up this issue! The reason why Switch component in the Web preview is rendered wrong is because `react-native-web` Switch uses different types (`trackColor` in core is an Object which contains Colors, but in `react-native-web` it's a Color) and uses additional properties not available for platforms build-in in the core package. 

Those properties cannot be added to the Snack because will be ignored on mobile platforms (which could add even more confusion). Also those properties cannot document because the code behind them is not a part of React Native. As a solution I'm going to disable Web preview for the Switch examples.

If you are interested in developing for the web using React Native I would recommend visiting `react-native-web` documentation. There are a lot more examples and configuration options described: 
* http://necolas.github.io/react-native-web/docs/?path=/docs/components-switch--active-thumb-color

**Comment by chanonroy** [comment]
> @chanonroy Thank you for bringing up this issue! The reason why Switch component in the Web preview is rendered wrong is because `react-native-web` Switch uses different types (`trackColor` in core is an Object which contains Colors, but in `react-native-web` it's a Color) and uses additional properties not available for platforms build-in in the core package.
> 
> Those properties cannot be added to the Snack because will be ignored on mobile platforms (which could add even more confusion). Also those properties cannot document because the code behind them is not a part of React Native. As a solution I'm going to disable Web preview for the Switch examples.
> 
> If you are interested in developing for the web using React Native I would recommend visiting `react-native-web` documentation. There are a lot more examples and configuration options described:
> 
> * http://necolas.github.io/react-native-web/docs/?path=/docs/components-switch--active-thumb-color

Thanks for clarifying! Many thanks @Simek 😃
