### ISSUE TITLE
Linking and expo

### ISSUE THREAD

**Issue by sa1dai** [facebook/react-native-website#2082]
## Description

React Native [Linking](https://reactnative.dev/docs/linking) documentation:

> The following section **only** applies to projects with native code exposed.

![screenshot_404](https://user-images.githubusercontent.com/47157550/88022764-89e03200-cb38-11ea-8539-af8e9cca1981.png)

Expo [Linking](https://docs.expo.io/versions/v38.0.0/sdk/linking/) documentation:

> This module is **an extension** of the React Native Linking module, meaning that **all methods in the RN module can be accessed via Linking**, on top of the extra methods provided by Expo (detailed here).

![screenshot_405](https://user-images.githubusercontent.com/47157550/88041759-85754280-cb53-11ea-94d7-efb84e678438.png)

I think its confusing, that React Native docs states that section applies only for project with native code. I can use Linking from 'react-native' in my Expo managed project and it will work.

## Documentation version

0.60, 0.61, 0.62, 0.63

**Comment by Simek** [comment]
Hi @sa1dai, thank you for bringing this issue up, let me clarify that:
* `Linking` module from `react-native` will not work in Expo app, 
* Not every `Linking` module method from `expo` will work in bare React Native app.

The sentence on the React Native website is correct (it warns Expo users that they can't uses that module from the core), but how `Linking` module from Expo works or what it mimics, it's just the Expo developers decision. 

The source of the problem is in the sentence in Expo documentation so I think that you should create the issue in the Expo repository instead and ask for or propose a rephrase in there.

**Comment by sa1dai** [comment]
> Linking module from react-native will not work in Expo app,

It's not  true.  Linking module from react-native can work in Expo app in managed flow (without native code). That is why I opened issue in RN docs.
