### ISSUE TITLE
guides https://reactnative.dev/docs/native-modules-android and https://reactnative.dev/docs/native-modules-setup are broken

### ISSUE THREAD

**Issue by stickoutapp** [facebook/react-native-website#2107]
## Description

This guide rely on Native Module Setup, which in turn rely on the community tool called Bob. When running Bob in the current version, there are additional steps not mentioned in the guide, and the template project created works with Kotlin, not java.

So the example code for the The Toast Module and everything that follows is not applicable.

## Documentation version
React Native
0.63

**Comment by gedeagas** [comment]
Nice catch @stickoutapp. Interesting find.

@Simek With https://github.com/react-native-community/bob migrating away from java to kotlin should we update the docs to use kotlin instead of java?

![Screenshot from 2020-08-05 00-26-53](https://user-images.githubusercontent.com/8868908/89325011-64afff80-d6b2-11ea-9376-6c5f1f4a8feb.png)

**Comment by Simek** [comment]
Refs #706, #1064, #1569, #1708 and more.

The Native Modules Setup, Native Modules Android and Native Modules iOS pages are certain not the best and well updated pages. There are complains about them for a long time but unfortunately there is also no one who want to correct, improve or rewrite those pages. 

I think that there reason for this might be the fact that most of RN users would never need to create their own Native Module (it's a niche in a global usage spectrum), so there is not a lot of knowledge about the whole process in the community and there are not many developers who consider themselves experienced with Native Modules.

And personally I think that my knowledge about Native Modules and experience with them is lacking too much to update those guides.

> @Simek With https://github.com/react-native-community/bob migrating away from java to kotlin should we update the docs to use kotlin instead of java?

I think that it would be nice to add Kotlin and preserve Java (until it's officially supported). The same situation is with iOS, where the current guide is based on Objective-C, and the guide for Swift projects is missing.

**Comment by gedeagas** [comment]
@Simek My team and I are really happy to help with documenting native modules. Here is my take regarding this issue. 

**The first option. (Less effort, High impact).** 
1. Change bob with https://github.com/brodybits/create-react-native-module. 
Because bob is very opinionated and completely abandon java, changing the tools to https://github.com/brodybits/create-react-native-module would be the easiest way to have proper documentation compatibility with existing docs. 

**The second option. (High effort, High impact).** 
2. Add Kotlin and Swift documentation while still preserving ObjC and Java. This option will required a very high effort to write and maintain (4 languages). But then again if we use `bob` the old Java guide is still broken and probably will make user confused. As for iOS `bob` support both ObjC and Swift. 

My main concern with the second option is that in the coming months hopefully `react-native` will ship `Fabric` and `TurboModules`. With `Paper` being abandoned i afraid that writing a complete and proper doc on Native Module while still using the old `Paper` architecture will become a pointless endeavor.  Then again I don't know the plan from the `react-native` team regarding this. 

Anyway, My team and I are ready to help <3. I know that Native Modules is definitely a "niche"  in a global usage spectrum. But as the application grows, so does the need. And having kickass documentation on Native Modules would definitely help.

And just a random thought, I really loved the ilustration that @rachelnabors did on getting started page. Would be very awesome to have those kinds of illustration on the new docs for `TurboModules` and `Fabric` <3.

**Comment by betoharres** [comment]
I'd like to give my cent as RN user just starting to make Native Modules for RN ecosystem:
First thing I did was to check official docs, and I rapidly executed bob create command to bootstrap my new project.
Second thing I did was to try to follow along the docs on how to build such native module, and to be honest, it didn't helped me to show a simple native view and I got confused because of the java/kotlin differences.
It's not all bad though, I think it can vaguely guide the novices.

**Comment by sajaddp** [comment]
Dear @Simek, Is there a scheduled plan for updating this page?

**Comment by Simek** [comment]
Hey @sajaddp, there is no schedule, but someone already started working on the update for Native Modules pages - #2261 🙂

**Comment by cortinico** [comment]
I believe this can be closed as #2261 was merged right @Simek ?

**Comment by Simek** [comment]
Yup, I think it's fine to close this issue for now (the Bob reference has been remove, however the updated guides are still using Java, but this should be fine after Bob removal, if I understand the issue correctly). 

@stickoutapp If you think that the current guides are still lacking some information or there are incorrect in some way, please create a new issue. 🙂
