### ISSUE TITLE
Can we keep documentation sites about documentation?

### ISSUE THREAD

**Issue by damusix** [facebook/react-native-website#2210]
I would like to politely and respectfully propose we keep politics out of our work environments. I'm all for showing support for what you believe in, but it would be nice if we could keep code docs about code docs and not politics. Not everyone agrees with the principles or political views of BLM and it's a bit annoying / triggering / distracting to see my favorite tools constantly spamming me political messages while I am working. Please consider removing political messages from site's banner.

**Comment by doxpopuli** [comment]
What, do you, like, um, not care about black people or something? Sorry (not sorry) to make you uncomfortable, but the RN dev team (some of the most privileged human beings -- mostly white, mostly male, all ridiculously well compensated for their labor -- to ever walk this earth) _will_ waste precious screen real estate on your cheap laptop's low resolution display (because you aren't privileged enough to afford anything better) on a message that you would only otherwise hear from almost all of corporate America, and you will like it, bigot. Because what's most important to the React Native dev team is that you know that they really, really love black people more than you do. I mean, where's your BLM banner, huh?

Just reading this absurd complaint is making it hard for me to breath. Not a "police officer using an approved form of neck restraint" inability to breath, I admit, but more of the "combination of fentanyl overdose and strenuous physical exertion from resisting arrest" kind.

**Comment by gaearon** [comment]
Thanks for your concern. We’ve made a decision to add the banner and we understand there would always be people who agree or disagree with it because this decision is not neutral. There’s not much to be gained from discussing this, and as you can see above, threads like this, even when well-intentioned, tend to attract trolls. I think it would be nice to make the banner dismissible, especially given that many people have contributed, but I’m going to lock this issue to prevent it from attracting trolls.
