### ISSUE TITLE
Wrong links in the partners section

### ISSUE THREAD

**Issue by ricardobeat** [facebook/react-native-website#2285]
## Description

The link to Callstack under the **Facebook Supported, Community Driven** section in the index page (https://reactnative.dev) actually points to microsoft.com. Most curiously, the "2nd highest" link points to callstack.com.

## Documentation version

(index page)

**Comment by Simek** [comment]
Hi @ricardobeat, thank you for reporting the issue. It looks like there is a problem with rehydration (React), code for this page looks fine:
* https://github.com/facebook/react-native-website/blob/master/website/src/pages/index.js#L439

Same with the SSR output:
![unknown](https://user-images.githubusercontent.com/719641/97697126-daa3e700-1aa6-11eb-9d5b-582b72fb7a23.png)

I will try to mitigate this effect locally and I will push the fix if I will be able to correct this.

**Comment by slorber** [comment]
On reactnative.dev homepage:

![image](https://user-images.githubusercontent.com/749374/97697186-f0191100-1aa6-11eb-8d68-0b4992f55da7.png)

You are right, the Callstack link links to a Microsoft domain, and other links are interverted.

Yet:
- The code is fine (https://github.com/facebook/react-native-website/blame/master/website/src/pages/index.js#L439)
- The SSR markup is fine.
- The links are fine if we navigate to the landing page.
- This only happens when refreshing/hydration the React page

This looks like a React hydration problem.
Maybe it's a React bug? 
Maybe RN/Docusaurus has a server/client markup mismatch producing weird behaviors? (joshwcomeau.com/react/the-perils-of-rehydration)

Hard to tell 🤪
