### ISSUE TITLE
In the example of TouchableNativeFeedback component documentation, the error is reported as Ripple is not a function

### ISSUE THREAD

**Issue by JustaCattt** [facebook/react-native-website#2305]
![image](https://user-images.githubusercontent.com/55068656/97974819-1de1bb00-1e03-11eb-9b31-d5364061f1a1.png)

**Comment by Simek** [comment]
Hi @JustaCattt, 

the problem is that (for some unknow for me reason) you are able to see all the platforms (iOS, Android, Web) in the Android platform example. 

For me only Android option is visible on the https://reactnative.dev/docs/touchablenativefeedback page and this is what the `supportedPlatforms` params says: https://github.com/facebook/react-native-website/blame/master/docs/touchablenativefeedback.md#L16

But also looking at your screenshot it looks like you are using the [React Native Archive](https://archive.reactnative.dev) website, not the current one.

#### Preview
<img width="634" alt="Screenshot 2020-11-03 113813" src="https://user-images.githubusercontent.com/719641/97975665-c2470b80-1dc9-11eb-9b3e-b23983dc3c69.png">

**Comment by JustaCattt** [comment]
Oh, no wonder!&nbsp; Thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebook/react-native-website"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 晚上6:45
收件人:&nbsp;"facebook/react-native-website"<react-native-website@noreply.github.com&gt;;
抄送:&nbsp;"yu"<479999519@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [facebook/react-native-website] In the example of TouchableNativeFeedback component documentation, the error is reported as Ripple is not a function (#2305)





 
Hi @JustaCattt,
 
the problem is that (for some unknow for me reason) you are able to see all the platforms (iOS, Android, Web) in the Android platform example.
 
For me only Android option is visible on the https://reactnative.dev/docs/touchablenativefeedback page and this is what the supportedPlatforms params says: https://github.com/facebook/react-native-website/blame/master/docs/touchablenativefeedback.md#L16
 
But also looking at your screenshot it looks like you are using the React Native Archive website, not the current one.
 
Preview

**Comment by Simek** [comment]
It looks like the correct repository for this issue report is:
* https://github.com/reactnativecn/react-native-website
