### ISSUE TITLE
Component props inheritance should be shown on the right side next to props list

### ISSUE THREAD

**Issue by SurmaAa** [facebook/react-native-website#2399]
## Description
I think component props inheritance should be shown on the right side next to props list e.g.

## What is the problem?
The `TouchableHighlight` inherits props from `TouchableWithoutFeedback` but there is no information in the docs right side (https://reactnative.dev/docs/touchablehighlight) that it's inherited, the new learner has to scroll down to get know about this which isn't obvious.

## How can we address it?
By adding a information about inheritance. Maybe like in the picture?
![Imgur](https://imgur.com/90aWlv9.jpg)

## Why is it important?
I think it's important for new learners like me because they could find something faster. I spent ~10 minutes thinking about why example shows `onPress` prop and there is nothing like this in the props list, till I scrolled down and finally there was the information about inheritance

## Who needs this?
I think the new learners mostly 

## When should this happen (use version numbers if needed)?
I used `0.63` docs version

**Comment by Simek** [comment]
Hi @SurmaAa, 

the inherited props are already visible in the `next` version docs. The changes has been implemented in #2168. Hope this improves the readability and fixes the issue you are mentioning.

Note: In the previous version of websites clicking on the link in ToC was redirecting users strait to the parent components page, where in new version Toc links scroll to the section where link to the parent component props is located. This has been reported to the Docusaurus and will be fixed in the future.

Refs: #2190

**Comment by SurmaAa** [comment]
Thanks, cool
