### ISSUE TITLE
Running On Device 

### ISSUE THREAD

**Issue by pedrocardoz0** [facebook/react-native-website#2471]
At the page _https://reactnative.dev/docs/running-on-device_. Is it really necessary to run with `npx` ?

**Comment by Paraplux** [comment]
Hi, 

npx helps you avoid versioning, dependency issues and installing unnecessary packages that you just want to try out.

I think you go for npx or npm, depends on what you want to do after next.

[Source](https://www.freecodecamp.org/news/npm-vs-npx-whats-the-difference/)

**Comment by Simek** [comment]
Hi @pedrocardoz0, 

it's not necessary in all cases, but generally it's recommended. Since CLI have been extracted from the `react-native` package, in most cases, it should not be installed globally - removing the `npx` from the command would result in resolving globally linked (on the machine) or locally proxied installation of React Native (if any) and could lead to unwanted issues.

You can read more about `npx` and React Native, for example, in this Medium post:
https://medium.com/unpacking-react-native/initialising-projects-with-npx-e7515604364a
