### ISSUE TITLE
Minor documentation issue

### ISSUE THREAD

**Issue by techunits** [facebook/react-native-website#2520]
## Description

In the Getting Started documentation for typescript, the project creation from TS template command is not correct. It gives issue that template not found. The correct command I have realized as follows:

`npx react-native init scmobile --template typescript`

**Node Version:** `14.x`

**Link to page:** [https://reactnative.dev/docs/typescript](https://reactnative.dev/docs/typescript)

## Documentation version

`Version: 0.63`

**Comment by Simek** [comment]
Hi @techunits, this is the known issue and unfortunately the problem is with you local setup. Please make sure you have read and follow the note on the page:
<img width="617" alt="Screenshot 2021-03-01 101935" src="https://user-images.githubusercontent.com/719641/109476848-a69dfa00-7a77-11eb-96c5-e285c575ea34.png">

If the tip in there won't solve your problems, please refer to:
* https://github.com/react-native-community/react-native-template-typescript/issues/80
* https://github.com/react-native-community/react-native-template-typescript/issues?q=is%3Aissue+not+found+is%3Aclosed+
