### ISSUE TITLE
Building React Native document link for android not working

### ISSUE THREAD

**Issue by bw-space** [facebook/react-native-website#2620]
## Description
Link given under react-native/ReactAndroid for Building React Native for Android docs, which points to https://reactnative.dev/docs/building-from-source.html#android
shows page not found.

**Comment by Simek** [comment]
Hi @bw-space, thank you for the report! 👍 

It looks like the problematic link in the Readme file has been fixed in https://github.com/facebook/react-native/pull/31901 and, as Luis pointed out, the page has been moved to core repository GitHub Wiki (quite a while ago). 

For now, this should be a sufficient fix. We can add a redirect in the future, if there will be more reports regarding this broken link. 🙂
