### ISSUE TITLE
Low Contrast on React Native components diagram 

### ISSUE THREAD

**Issue by brooksbecton** [facebook/react-native-website#2706]
## Description

As a person who uses dark mode frequently, when I go to https://reactnative.dev/docs/intro-react-native-components and scroll to the diagram at the bottom, the "React Components" text is hard to see. 

<img width="1526" alt="Screen Shot 2021-07-28 at 8 06 48 AM" src="https://user-images.githubusercontent.com/9373516/127319473-abd17eff-1cc2-43e8-93e1-3f32f2ce66a3.png">

## Documentation version

0.64

**Comment by brooksbecton** [comment]
I'd be happy to work on this one. 
Please let me know how I can help out.

**Comment by luism3861** [comment]
> I'd be happy to work on this one.
> Please let me know how I can help out.

hi @brooksbecton thanks for the issue ,i think this is an image i don't know if it exist in dark mode 
@Simek can answer this issue

**Comment by Simek** [comment]
Hi @brooksbecton, thank you for reporting this issue!

 I have decided to fix the by myself, because there were a multiple options to handle this (besides `ThemedIamge`, we can also use CSS overwrite based on current theme, alter main image design etc.) and it was hard to tell which option will be the best to fix this case without experimenting by myself. 

Also to edit the base design files you need a paid tool (Adobe Illustrator or Sketch), and usually we do not request such changes from the community. Hope you find the fix im PR satisfying! 🙂
