### ISSUE TITLE
unwanted website scroll to top on refocus

### ISSUE THREAD

**Issue by slorber** [facebook/react-native-website#2807]
## Description

On Chrome 94 + MacOS 11.5, it's been reported that the window smooth scrolls to top when window regains focus:

https://user-images.githubusercontent.com/55398995/136369579-58d4a434-da53-487c-a529-2113d62aa3db.mov

Initially reported here by @vikramvi & @Josh-Cena: 
- https://github.com/facebook/react-native-website/issues/2771
- https://github.com/facebook/react-native-website/issues/2806

https://reactnative.dev/docs/environment-setup

I can't reproduce myself.

## Documentation version

0.66

**Comment by slorber** [comment]
I am not able to reproduce this bug

@vikramvi, @Josh-Cena are you able to reproduce this:
- on another browser?
- on another computer?
- on the Docusaurus.io website?
- with/without incognito?
- with all browser plugins disabled? (or anything that can mess up with your browser?

**Comment by slorber** [comment]
@Josh-Cena the video above shows something like multi-desktop keyboard navigation or something: how can I set this up locally?. 
Are you both using that? Can this be reproduced by changing browser tabs or just switching programs without virtual desktops?

Are you using a shortcut that involves pressing `command + up`?

**Comment by Josh-Cena** [comment]
Removing this part fixed it for me:

https://github.com/facebook/docusaurus/blob/e1b4da04fe88767d52f21bf1f043af308e7bfbd2/packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx#L77-L91

So can confirm it's the scroll into viewport problem. This is because the `handleTabChange` is fired `onFocus`, but when switching browser tab / window the component also loses / regains focus
