### ISSUE TITLE
Create Fragment improvement 

### ISSUE THREAD

**Issue by wilsolutions** [facebook/react-native-website#2838]
It would be more clear if we add more example to the new "Create Fragment" section.

There is no example of `CustomView customView;`, what is it? A simple class that extends View? 
It would be more clear if we have an example for it as well...

I have ran into a problem were the View stay on the very back of the Views hierarchy, I have more details here:
https://stackoverflow.com/questions/69771856/android-fragment-not-displayed-in-react-native-app 

## Documentation version
0.66

**Comment by arjun1194** [comment]
where is the link to the updated documentation ??

**Comment by Simek** [comment]
@wilsolutions Thank you for the work on the new example, good job! 👍 

Since the PRs have been merged in I'm going to close this issue.

---

@arjun1194 To see the latest changes to the docs you need to switch to the `next` version from the docs version selector.

Here is the direct link: https://reactnative.dev/docs/next/native-components-android
