### ISSUE TITLE
update choco package `openjdk11` to `microsoft-openjdk11`

### ISSUE THREAD

**Issue by khali70** [facebook/react-native-website#3379]
according to the choco `openjdk11` is deprecated 
which leads to the problem of unrecognizing android-studio with react-native 
![image](https://user-images.githubusercontent.com/59835449/197101366-3c7b6731-da25-455d-ab20-717cd879569a.png)

## solution
https://github.com/facebook/react-native-website/blame/main/docs/_getting-started-windows-android.md#L20
```diff
- choco install openjdk11
+ choco install microsoft-openjdk11
```

### see choco packges for [openjdk11](https://community.chocolatey.org/packages?q=openjdk11)

**Comment by cortinico** [comment]
> according to the choco `openjdk11` is deprecated

I'd love to have someone from Microsoft cross-check this before we land it.

**Comment by mganandraj** [comment]
@cortinico, I have been using Microsoft builds of OpenJDK 11 for RN android builds for a while now, but I use winget instead of choco.
`winget install Microsoft.OpenJDK.11`

Choco distribution of Microsoft.openjdk11 looks good and trusted too .. If @khali70 has already tried and works well, I'd back this PR.

**Comment by cortinico** [comment]
Great! @khali70 don't you mind sending a PR over to update the website?
