### ISSUE TITLE
InteractionManager.runAfterInteractions() is not working properly on web?

### ISSUE THREAD

**Issue by artus9033** [facebook/react-native-website#3924]
## Description

`InteractionManager` documentation [states the following](https://reactnative.dev/docs/interactionmanager):

> **Note**: `InteractionManager.runAfterInteractions()` is not working properly on web. It triggers immediately without waiting until the interaction is finished.

Which is most likely outdated.

## What is the problem?

The docs [here] state that `InteractionManager.runAfterInteractions()` is not working properly on the web. However, [this issue](https://github.com/necolas/react-native-web/issues/2399) resulted in a [PR being introduced and merged](https://github.com/necolas/react-native-web/pull/2425). The code introduced in this PR seems to be present at the moment, e.g. [here](https://github.com/necolas/react-native-web/blob/a3ea2a0a4fd346a1b32e6cef527878c8e433eef8/packages/react-native-web/src/exports/InteractionManager/index.js). Based on a practical test I performed, it indeed seems that this PR is present in the current version of `react-native-web` and works properly, since the task queue for `InteractionManager` has been implemented and performs as intended.

## How can we address it?

Verify this proposal and update the documentation by stating that this invalid behaviour applies to `react-native-web` versions below `0.19`.

## Why is it important?

It may cause confusion.

## Who needs this?

Every user reading the documentation.

## When should this happen (use version numbers if needed)?

N/A

**Comment by gedeagas** [comment]
I recall encountering a pull request for `InteractionManager` a while ago, specifically around the time when Rachel initiated the Component Docs Drive. In that PR, the example code specifically configured the `supportedPlatforms` for snack to only include iOS and Android. This exclusion of the web platform was intentional, stemming from the issues with `InteractionManager.runAfterInteractions()` not functioning correctly on web platforms.

In my view, **documentation specifically addressing `InteractionManager ` for `react-native-web` should be included in the `react-native-web` documentation, rather than the main `react-native` documentation**. This distinction is important for clarity and accuracy.

Interestingly, this issue has been resolved in react-native-web. Therefore, I suggest removing the previous notes regarding this issue from the documentation. This update won't be detrimental in any way; in fact, it will help avoid potential confusion for users. 

@lunaleaps, I would like to get your opinion on this matter. Apologies for the direct mention, but I thought it was pertinent to involve you in this discussion
