### ISSUE TITLE
Watchman dependency not mentioned on the first getting started page

### ISSUE THREAD

**Issue by 814k31** [facebook/react-native-website#4]
I followed the instructions
``` npm install -g create-react-native-app
Then run the following commands to create a new React Native project called "AwesomeProject":
create-react-native-app AwesomeProject

cd AwesomeProject
npm start
```

However it didn't work because there was no mention of watchman (in this page specifically)
Is it possible to add that?
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by hramos** [comment]
There's several permutations depending on the platform you're developing on and the platform you're targeting. Can you tell us more about which version of the guide you followed? Watchman is mentioned in the iOS and macOS version of the guide, for example.

**Comment by hramos** [comment]
Sorry - you're following the Quick Start it seems. Watchman should not be required by CRNA unless something changed recently. Can you tell us more about what did not work?

**Comment by brentvatne** [comment]
@hramos - it seems that on some machines it's needed :\ if we're unable to start the packager due to fs event notif limits we do provide specific instructions for how to get it work without watchman and also link to watchman -- https://github.com/react-community/create-react-native-app/blob/882f1d23766b827429b2b1fbfd4afc513796a652/react-native-scripts/src/util/packager.js#L77-L116

the bet we're making here is that people will have less problems not installing watchman and following the error message than they will if they try to install watchman (which people often have problems with on Windows/Linux). neither solution is perfect. ideally we'd bundle something like watchman (perhaps even watchman itself) in CRNA and scope it so it doesn't deal with any global system state

**Comment by brentvatne** [comment]
cc @dikaiosune

**Comment by 814k31** [comment]
Yeah I tried to run it on my mac book air (I think its like an 09 or something)
I'll uninstall watchman a bit later and get the error message back if you need however I found the error was caused by not having watchman on my machine which worked fine after installing it

In regards to watchman being purposely left out of the docs, feel free to close this issue.
I just thought I'd create it incase you weren't aware of the error message

**Comment by dikaiosune** [comment]
This should probably be tracked somewhere else (metro maybe?) but it would be very nice to either replace watchman with a non-global per-process watcher, or to bundle watchman as platform specific npm packages and use its `--state-dir` and `--foreground` flags to isolate it to a specific packager instance. This would get people more accurate file watching without needing to install it separately from CRNA and without the global state debugging dance that usually comes with watchman's default configuration.

**Comment by ecreeth** [comment]
@814k31 you can close this issue, watchman is already mentioned!
