### ISSUE TITLE
Missing documentation of background geolocation for Android

### ISSUE THREAD

**Issue by AmeerHamzaRiaz** [facebook/react-native-website#415]
In Geolocation [documentation](https://facebook.github.io/react-native/docs/geolocation.html), it is stated that geolocation can be made compatible to be run in background for IOS but does not states that for Android whether it works in background or not.

**Comment by Simek** [comment]
Hi @AmeerHamzaRiaz. 

I'm going to close this issue because Geolocation has been removed from the core package [within `0.60` release](https://reactnative.dev/blog/#lean-core-removals). You can check the package and its documentation [here](https://github.com/react-native-community/react-native-geolocation).
