### ISSUE TITLE
Expo iOS Simulator Crashes Every Time with ActionSheetIOS

### ISSUE THREAD

**Issue by Urmin-tagline** [facebook/react-native-website#4150]
Description:
I'm experiencing a consistent issue where the Expo iOS simulator crashes every time I try to use ActionSheetIOS. This issue occurs even with the simplest usage of ActionSheetIOS, following the documentation provided at https://reactnative.dev/docs/actionsheetios. Additionally, it seems this issue is present not only in this specific scenario but everywhere in the documentation where the Expo iOS simulator is used.

React Native version: [e.g., 0.74.0]

**Comment by cortinico** [comment]
Hi @Urmin-tagline 
Thanks for reporting this issue.

It seems like this issue is actually unrelated to the React Native Website. Please open this issue against this other repository:

https://github.com/expo/expo/issues
https://github.com/react-native-community/cli/issues
https://github.com/software-mansion/react-native-reanimated/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
