### ISSUE TITLE
Add docs for how to easily test & use react native forks

### ISSUE THREAD

**Issue by kelset** [facebook/react-native-website#653]
More clear guidelines on how to do this will allow the community to make patch or share feature easily.

Related issue:
#21776
#21967

---

Original issue: https://github.com/facebook/react-native/issues/22030 by @gengjiawen.

**Comment by bartolkaruza** [comment]
Relevant issue from rn repo: https://github.com/facebook/react-native/issues/22118

**Comment by bartolkaruza** [comment]
In addition to documentation, would it help if this was a script that handles setting up a fork? This script could make sure you are not on the facebook/react-native repo, check the common error of wrong Android NDK version, remove the relevant line from .gitignore and run the `./gradlew :installArchives` step.

**Comment by kelset** [comment]
Sounds like a good second step, but I think that we should start with the docs first 😄

Btw what's this step about?
>  run the ./gradlew :installArchives step

I don't think I've ever run it 😅

**Comment by bartolkaruza** [comment]
It's the [gradle task](https://github.com/facebook/react-native/blob/master/ReactAndroid/release.gradle) that builds the Android .aar/.jar binaries. They are not committed in the source repo, only built on publishing to NPM. As far as I know, it's the only part of the RN that makes this forking business a bit complicated, because all other dependencies are just there in the main repo as source files.

**Comment by kelset** [comment]
Understood - @grabbou once the PR is up would you mind doublechecking it? I feel you have way more experience than me in this 😅

**Comment by grabbou** [comment]
Sure, would love to take a look. In fact, at Callstack, we are constantly setting up various React Native forks for internal purposes and this process is usually taking more than we would like it to take. Happy to look into any improvements.

**Comment by bartolkaruza** [comment]
I can write the first draft tomorrow if no-one else has anything written up yet? I want to take the time to run through the process end-to-end on a current version. It has been a few RN releases since I've had to set up a fork.

**Comment by gengjiawen** [comment]
Also for non android dev and ci users, we can use docker to demonstrate how to do the android release.
see https://github.com/react-native-community/discussions-and-proposals/pull/36.

**Comment by bartolkaruza** [comment]
I've noticed gradle 4.4 hanging on the `installArchives` task, in the configuration phase. This symptom can be resolved by using the `--no-daemon` flag, but I think there is something wrong in the gradle plugins that is causing this in the first place.

**Comment by gengjiawen** [comment]
Building aar using docker
```
docker run --rm --name rn-build -v $PWD:/pwd -w /pwd gengjiawen/react-native /bin/sh -c "./gradlew installArchives"
```

**Comment by gengjiawen** [comment]
@bartolkaruza Maybe network issue, I have not run into this issue using docker.

**Comment by bartolkaruza** [comment]
It could be an OS difference as well, isn't docker running a Linux base image? I was building on OSX.

**Comment by kelset** [comment]
BTW, check also this section https://facebook.github.io/react-native/docs/building-from-source as I feel there may be some overlap.

**Comment by bartolkaruza** [comment]
@gengjiawen I've moved it to a separate page and added you as contributor to my fork of the website, feel free to add your addition/modification. I've split the page into two sections; building/publishing. Building suggests `building from source` or using your docker image, recommending the latter.

**Comment by gengjiawen** [comment]
@bartolkaruza Just create the pr, I will review it.

**Comment by bartolkaruza** [comment]
> @bartolkaruza Just create the pr, I will review it.

#675

**Comment by joshglenn** [comment]
It would definitely be nice to have some documentation on how to build react native from source. The [docs](https://github.com/facebook/react-native/wiki/Building-from-source) only tell how to build the android side of things. 

What about iOS? Any special build steps?

How is the project structured?

My biggest hurdle right now with this topic:

I want to know how to use my own fork of the react-native npm package as a dependency in my own react-native project. Then, after getting to know it and understanding it, maybe I'll be able to contribute.

So, I try it using `yarn add file:../path/to/my/react-native/fork`. When I do this and then run `yarn start` and `yarn ios`, I get all kinds of errors. Then, I install the same version of react native again from npm, and everything works fine.

I am not writing this to make a separate issue out of my immediate problem-at-hand. But the problem I am facing at the moment underscores the need for docs to help potential contributors. (I have spent 5 hours or more on this and have came up empty so far)

Specifically: 

- help us get to know the structure of the react-native project
- the specific steps to take in order to build for iOS
- the specific steps needed to fork the `react-native` repo, use it in our own project, make a change to it, and see the result.
