### ISSUE TITLE
React Navigation Tutorial 

### ISSUE THREAD

**Issue by NPadrutt** [facebook/react-native-website#662]
Hi

I'm a complet beginner with React Native / WebApps and playing around with the tutorials to test out some basic concepts. One of the first tutorials I did was the one about navigation: https://facebook.github.io/react-native/docs/navigation#react-navigation. 

After having added all the code, I had several errors on launch in the end due to several missing imports and export declarations. For example the `export default` for the screens or the imports for the Screen variables.

Are they left out to have only the minium or where they accidentally left out? If the latter, would it make sense to update the code samples to include them?

**Comment by KeevanDance** [comment]
Correct, the full code for those examples would be something like this (assuming i don't make a typo)

`// App.js`

```javascript
import {createStackNavigator, createAppContainer} from 'react-navigation';
import HomeScreen from './screens/HomeScreen';
import ProfileScreen from './screens/ProfileScreen';

const MainNavigator = createStackNavigator({
  Home: {screen: HomeScreen},
  Profile: {screen: ProfileScreen},
});

const App = createAppContainer(MainNavigator);

export default App;
```

`// HomeScreen.js`

```javascript
import React from 'react';
import {Button} from 'react-native';

class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome',
  };
  render() {
    const {navigate} = this.props.navigation;
    return (
      <Button
        title="Go to Jane's profile"
        onPress={() => navigate('Profile', {name: 'Jane'})}
      />
    );
  }
}

export default HomeScreen;
```

and the structure would be similar for ProfileScreen as well...

Hope this is what you were talking about?

First thing, the react-navigation docs are out of date as November 17, 2018 because of the 3.0 release (I submitted a PR to update the docs). As far as the minimal code goes, I think a lot of that code is left out, because it is probably assumed you have some javascript or some react familiarity before jumping into React Native.

**Comment by NPadrutt** [comment]
Thanks keevan for the detailed answer. This was exactly what I was talking about.
