### ISSUE TITLE
[Images] How are images directories chosen?

### ISSUE THREAD

**Issue by Bhullnatik** [facebook/react-native-website#69]
I noticed a lot of images are not displayed correctly because the link doesn't exist, for example almost every image in [`Performance`](https://facebook.github.io/react-native/docs/performance.html) points to [`/docs/assets/`](https://github.com/facebook/react-native-website/tree/master/docs/assets) while the images are in [`/website/static/img`](https://github.com/facebook/react-native-website/tree/master/website/static/img).

The naming sounds weird to me (I think it should be in /docs/assets being ...assets of the documentation) so before sending a PR to fix I wanted to know **which folder should they be in?**

Ping @hramos as it seems you attempted to fix the links in https://github.com/facebook/react-native-website/commit/42162ef9dc849aac4a740ec1552f8391cd575892.

**Comment by hramos** [comment]
I already ran a script last month that went through every markdown file and ensured the necessary images were present in `/docs/assets`, but the 'static/img' directory needs some clean up. The images we are using in the docs are all in `/docs/assets` , therefore `/react-native/docs/assets/<image name>` should work.

In order to clean up the static img directory we just need someone to go through each file and remove whatever is not used by the website itself (e.g. logos in the site template).

**Comment by Bhullnatik** [comment]
@hramos I don't think your script worked because, I didn't try every page, but I can confirm it doesn't work for [`Performance`](https://facebook.github.io/react-native/docs/performance.html) and [`Debugging`](https://facebook.github.io/react-native/docs/debugging.html).
If you launch [`Performance 2. Reading the Trace`](https://facebook.github.io/react-native/docs/performance.html#2-reading-the-trace) you can see an image is missing due to linking to https://facebook.github.io/react-native/docs/assets/SystraceExample.png which doesn't exist while https://facebook.github.io/react-native/img/SystraceBadUI.png (/website/static/img/) exists.

**Comment by hramos** [comment]
I see what happened. See https://github.com/facebook/react-native-website/pull/70 where this should now be fixed, and hopefully the script will catch future errors.
