### ISSUE TITLE
DatePickerIOS option MinuteInterval are strings and not integers 

### ISSUE THREAD

**Issue by numyio** [facebook/react-native-website#797]
[https://facebook.github.io/react-native/docs/datepickerios#minuteinterval](https://facebook.github.io/react-native/docs/datepickerios#minuteinterval
)

Per the documentation, minuteInterval options are integers but minuteInterval expects a string element

Thank you!

Example: 

` <DatePickerIOS
          style={styles.dateScroll}
          date={this.state.chosenDate}
          mode='time'
          minuteInterval='10'
          onDateChange={
            this.setDate
          }
        />`

**Comment by charpeni** [comment]
It looks like `minuteInterval` is an integer following these flow types:

- [RCTDatePickerManager.m](https://github.com/facebook/react-native/blob/1151c096dab17e5d9a6ac05b61aacecd4305f3db/React/Views/RCTDatePickerManager.m#L39)
- [RCTDatePickerNativeComponent.js](https://github.com/facebook/react-native/blob/5f3afb9fe55ffdc726c64874d7c898cbed43d5ce/Libraries/Components/DatePicker/RCTDatePickerNativeComponent.js#L32)

Can you elaborate a bit more?

**Comment by Simek** [comment]
As @charpeni said before code tells us that only `integer` values are allowed. 

Since `DatePickerIOS` has been deprecated I suggest to retest this with recommended substitution package and report issue or invalid documentation [in this repo](https://github.com/react-native-community/datetimepicker).
