### ISSUE TITLE
can Text support multiple fontFamily

### ISSUE THREAD

**Issue by sophister** [facebook/react-native-website#800]
Hi, it seems web can not set **multiple** font families to `Text` style `fontFamily`, just like this

```javascript
const styles = {
    text: {
        fontFamily: "Roboto, PingFangSC-Thin, serif"
   }
}

<Text style={styles.text}>some text</Text>
```

I can't find some related doc from react native website

**Comment by rickhanlonii** [comment]
Hey @sophister, you're right this isn't supported

I think the best place to add it would be [here](https://facebook.github.io/react-native/docs/text#limited-style-inheritance) because we already talk about how fontFamily is handled (as well as below on the page where the prop is defined)

Are you interested in submitting a PR?

**Comment by sophister** [comment]
@rickhanlonii  I've submitted this PR [https://github.com/facebook/react-native-website/pull/802](https://github.com/facebook/react-native-website/pull/802), plz take a look

**Comment by cpojer** [comment]
Thanks!
