### ISSUE TITLE
Yarn Usage

### ISSUE THREAD

**Issue by hawthord** [facebook/react-native-website#956]
Please add a line under the Development Workflow header of https://github.com/facebook/react-native/wiki/How-to-Contribute instructing the user to navigate to the cloned repo folder before running the 'yarn' command. This is not clearly specified on either the React Native GitHub or the linked Yarn site.

This may make it difficult for an inexperienced developer to recognize whether they have installed the requisite project dependencies or not, as running yarn from another folder will produce the message 'Success'.

It is also unclear whether yarn updates packages installed by other package managers. For instance, [https://facebook.github.io/react-native/docs/getting-started.html](https://facebook.github.io/react-native/docs/getting-started.html) recommends installing React Native CLI using npm, and installing Node using Chocolatey.

**Comment by rickhanlonii** [comment]
Hey @hawthord! Thanks a ton for your feedback, I've updated the [wiki](https://github.com/facebook/react-native/wiki/How-to-Contribute) to instruct the user to open the cloned directory

I think it's ok for [Getting Started](facebook.github.io/react-native/docs/getting-started.html) to instruct to install with npm since it's a global install and not inside a repo using yarn, I think this is standard practice in the community

If you have a suggestion for improving that though feel free to tag me on a PR!

Thanks again 🚀
